# -*- coding: utf-8 -*-
"""Data Visualization Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sU9HLidmGeXIhARtlK0rX8mZYPj_5x8

# Project Name - Flipkart E-commerce Data

Project Type - EDA

Contribution - Individual

Name - - Shubham Giri

Section - - D2512

Roll Number - - A31

Reg. Number - - 12507973

# **Project Summary :-**

This project performs a comprehensive Exploratory Data Analysis (EDA) on an e-commerce product dataset from Flipkart, containing 20,002 records of products listed across multiple categories. The dataset includes detailed product information such as product name, category hierarchy, brand, retail price, discounted price, product description, ratings, and specifications.

The goal of this analysis is to uncover pricing patterns, understand discount strategies, identify popular product categories and brands, and explore how product attributes influence pricing and customer perception. By doing so, the project aims to provide valuable insights for e-commerce businesses, sellers, and analysts to optimize pricing strategies, improve product positioning, and enhance customer engagement.

Key areas explored:

*  Distribution of retail and discounted prices

*   Analysis of discount trends across different product categories

*   Category-wise product distribution and hierarchy insights




*   Identification of top brands and frequently listed products
*   Relationship between retail price and discounted price


*   Analysis of product ratings and their availability












*   Extraction of useful information from product descriptions and specifications
*   Detection of missing or inconsistent data within the dataset

# **GitHub Link -**

# Problem Statement

In the rapidly growing e-commerce industry, understanding product pricing, discount strategies, and customer preferences is essential for businesses to remain competitive. However, large-scale product datasets often contain complex, unstructured, and inconsistent information, making it difficult to extract meaningful insights.

This project aims to analyze an e-commerce dataset from Flipkart to identify key factors influencing product pricing, discounts, and category performance. The challenge lies in cleaning and structuring the data, handling missing or inconsistent values, and uncovering patterns that explain how different attributes such as brand, category, and product specifications impact pricing and customer perception.

# **Define Your Business Objective?**

The primary objective of this project is to analyze the Flipkart e-commerce dataset to gain actionable insights into product pricing, discount strategies, and customer preferences. The analysis aims to help businesses understand how different factors such as product category, brand, and specifications influence pricing and sales attractiveness

# ***Let's Begin !***

# Import Libraries
"""

try:
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    import seaborn as sns
except ImportError as e:
    print("Error:", e)

sns.set_theme(style="whitegrid", palette="Set2")
plt.rcParams['figure.figsize'] = (10,6)

"""# Load Dataset

"""

try:
    df = pd.read_csv('/content/flipkart_com-ecommerce_sample.csv.zip')
    print("Loaded successfully")
except Exception as e:
    print("Error:", e)

df.head()

"""# Data Cleaning"""

df = df.drop_duplicates()
df = df.dropna()

# Convert price columns
df['retail_price'] = pd.to_numeric(df['retail_price'], errors='coerce')
df['discounted_price'] = pd.to_numeric(df['discounted_price'], errors='coerce')

# New feature
df['discount'] = df['retail_price'] - df['discounted_price']

df.dropna(inplace=True)

"""#Price Distribution -"""

sns.histplot(df['discounted_price'], bins=30, kde=True)
plt.title("Discounted Price Distribution")
plt.show()

"""Why?

Understand pricing spread
Insights: Most products are mid-priced
Impact:
Positive: Identifies target pricing
Negative: High competition in same range

#Product Category Count
"""

top_cat = df['product_category_tree'].value_counts().head(10)
sns.barplot(x=top_cat.values, y=top_cat.index)
plt.show()

"""Why? Identify dominant categories


Insights: Few categories dominate

Impact:
Strong demand areas
Overcrowded competition

#Discount Distribution
"""

sns.histplot(df['discount'], bins=20)
plt.show()

"""Insights: Moderate discounts common
Impact: Balanced pricing strategy

#Ratings Distribution
"""

sns.histplot(df['product_rating'], bins=10)
plt.show()

"""Insights: Most ratings between 3–4

Impact: Scope for improvement

#Price vs Rating
"""

sns.scatterplot(x='product_rating', y='discounted_price', data=df)
plt.show()

"""Insights: Weak relationship


Impact: Price ≠ quality always

#Retail vs Discounted Price
"""

sns.scatterplot(x='retail_price', y='discounted_price', data=df)
plt.show()

"""Insights: Strong linear relation
Impact: Consistent pricing

#Discount vs Rating
"""

sns.scatterplot(x='discount', y='product_rating', data=df)
plt.show()

"""Insights: Discounts don’t improve ratings
Impact: Quality matters more

#Category vs Price
"""

top_cat_list = df['product_category_tree'].value_counts().head(5).index
sns.boxplot(x='product_category_tree', y='discounted_price',
            data=df[df['product_category_tree'].isin(top_cat_list)])
plt.xticks(rotation=45)
plt.show()

"""Insights: Price varies across categories
Impact: Category-based pricing strategy

#Pairplot
"""

sns.pairplot(df[['retail_price','discounted_price','discount','product_rating']])
plt.show()

"""Insights: Confirms relationships visually
Impact: Better decision-making

#Boxplot (Outliers)
"""

sns.boxplot(x=df['discounted_price'])
plt.show()

"""Insights: High-price outliers present
Impact: Premium segment exists

#Product Rating Distribution
"""

sns.countplot(x='product_rating', data=df)
plt.title("Product Rating Distribution")
plt.xticks(rotation=45)
plt.show()

"""This chart is used to understand how product ratings are distributed across the dataset.

### What do you suggest the client to achieve Business Objective?

To achieve the business objectives, the client should focus on offering products in the mid-price range, as most customer demand lies there. Improving product quality can help increase ratings, which in turn boosts customer trust and engagement.

The client should also use discounts wisely instead of excessively, as discounts alone do not guarantee better ratings or sales. Additionally, promoting high-performing categories and products can improve visibility and overall sales. A balanced strategy focusing on pricing, quality, and customer satisfaction will help achieve better business results.

#  **Conclusion**

The analysis shows that pricing, category, and ratings significantly influence product performance. While discounts attract customers, they do not guarantee better ratings. Businesses should focus on quality and strategic pricing to achieve growth.
"""